[project]
name = "handwriting-dec"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [
    "flet>=0.85.2"
]

[dependency-groups]
dev = [
    "flet-cli>=0.85.2",
    "flet-desktop>=0.85.2",
    "flet-web>=0.85.2",
]

[tool.flet]
org = "com.mycompany"
product = "handwriting-dec"
company = "rycode"
copyright = "Copyright (C) 2026 by <rycode>"
permissions = ["camera", "microphone"]

[tool.flet.app]
path = "src"
